name: docker build

on:
    workflow_call:

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/download-artifact@v4
              with:
                  name: artefato_front_administracao
                  # path: your/destination/dir # por padrão, o arquivo é baixado para a workdir do GitHub Actions

            - name: Display structure of downloaded files
              run: pwd && ls -R .

            - name: setup Docker Build
              uses: docker/setup-buildx-action@v3

            - name: Docker Login
              uses: docker/login-action@v3
              with:
                  # Server address of Docker registry. If not set then will default to Docker Hub
                  registry: Docker Hub

                  # Username used to log against the Docker registry
                  username: ${{ vars.DOCKER_HUB_USER }}

                  # Password or personal access token used to log against the Docker registry
                  password: ${{ secrets.DOCKER_HUB_PASS }}

                  # Specifies whether the given registry is ECR (auto, true or false)
                  ecr: auto # optional, default is auto

                  # Log out from the Docker registry at the end of a job
                  logout: true # optional, default is true

            - name: Build and push Docker images
              uses: docker/build-push-action@v6
              with:
                  # Build's context is the set of files located in the specified PATH or URL
                  context: .

                  # Path to the Dockerfile
                  file: ./Dockerfile.prod

                  # Always attempt to pull all referenced images
                  pull: false # optional, default is false

                  # Faz o push da imagem para o Docker registry. Push is a shorthand for --output=type=registry
                  push: true # optional, default is false

                  # List of secret files to expose to the build (e.g., key=filename, MY_SECRET=./secret.txt)
                  #   secret-files: env=./.env # optional

                  # List of tags
                  tags: ${{ vars.DOCKER_HUB_USER }}/front_administracao:${{ github.head_ref || github.ref_name }}  # head_ref é o nome da branch para onde o pull request vai. ref_name é o nome da branch para onde o push vai

                  # GitHub Token used to authenticate against a repository for Git context
                  github-token: ${{ github.token }} # optional, default is ${{ github.token }}
